#                                   /   \
#  _                        )      ((   ))     (
# (@)                      /|\      ))_((     /|\                        _
# |-|                     / | \    (/\|/\)   / | \                      (@)
# | | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
# |-|                         '^`   (o o)  '^`                          | |
# | |                               '\Y/'                               |-|
# |-|                                                                   | |
# | |                            skDragon Recode                        |-|
# |-|                               by Sashie                           | |
# | |                                                                   |-|
# |_|___________________________________________________________________| |
# (@)              l   /\ /         ( (       \ /\   l                `\|-|
#                  l /   V           \ \       V   \ l                  (@)
#                  l/                _) )_          \I
#                                    '\ /'
#				                       v
#
# (Will only work for ops or anyone with the permission node 'skdragon.command')
Commands:
  # Enables or disables command usage
  Enabled: true

# Changing this number will reset the config file
Version: 1